/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DataImport } from './routes/data'
import { Route as BinsImport } from './routes/bins'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DataRoute = DataImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRoute,
} as any)

const BinsRoute = BinsImport.update({
  id: '/bins',
  path: '/bins',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bins': {
      id: '/bins'
      path: '/bins'
      fullPath: '/bins'
      preLoaderRoute: typeof BinsImport
      parentRoute: typeof rootRoute
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bins': typeof BinsRoute
  '/data': typeof DataRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bins': typeof BinsRoute
  '/data': typeof DataRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bins': typeof BinsRoute
  '/data': typeof DataRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bins' | '/data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bins' | '/data'
  id: '__root__' | '/' | '/bins' | '/data'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinsRoute: typeof BinsRoute
  DataRoute: typeof DataRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinsRoute: BinsRoute,
  DataRoute: DataRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bins",
        "/data"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bins": {
      "filePath": "bins.tsx"
    },
    "/data": {
      "filePath": "data.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
